name: Phonebook pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # BACKEND
      - name: Install backend dependencies
        run: npm install
        working-directory: phonebook-backend

      # FRONTEND
      - name: Install frontend dependencies
        run: npm install
        working-directory: the-phonebook

      - name: Build frontend
        run: npm run build
        working-directory: the-phonebook

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Trigger Render deploy
        run: curl -X POST "${{ secrets.PHONEBOOK_RENDER_DEPLOY_HOOK }}"
